data:
  shots: data/all.npy
  tmin: 0
  tmax: 6000
  time_step: 50
  sql_sig_names: ['t_ip_flat','ip_flat_duration','topology','time_of_shot','run',
                  'poh','pech','pbeam','btor','btorsign','ip','ipsign', 'betanmax']
  scalar_sig_names: ['dstdenp','dssdenp','dssdenest','ipsiptargt','ip','iptipp', 'bt', 'vloop',
                    'gasA', 'gasB', 'gasC', 'gasD', 'gasE', 'pfx1', 'pfx2', 'echpwr',
                    'efspsibdy1', 'efsg1psy', 'efsg1zx', 'efsg1rx', 'grsmean',
                    'bmspinj30l','bmspinj30r','bmspinj15l','bmspinj15r',
                    'bmspinj21l','bmspinj21r','bmspinj33l','bmspinj33r',
                    'DUSTRIPPED','N1ICWMTH', 'N1IIWMTH',
                    'dsifbonoff', 'dsiwdens', 'dsitgtsrc',
                    'bmifbonoff', 'bmipfbval',
                    'bmics30l','bmics30r','bmics150l','bmics150r',
                    'bmics210l','bmics210r','bmics330l','bmics330r',
                    'f1a', 'f2a', 'f3a', 'f4a', 'f5a', 'f6a', 'f7a', 'f8a',
                    'f1b', 'f2b', 'f3b', 'f4b', 'f5b', 'f6b', 'f7b', 'f8b',
                    'IL150', 'IU150', 'IL210', 'IU210', 'IL270', 'IU270',
                    'IL30', 'IU30', 'IL330', 'IU330', 'IL90', 'IU90'
                    ]
  stability_sig_names: ['n1rms','n2rms','n3rms']
  nb_sig_names: ['pinj','tinj']
  efit_profile_sig_names: ['qpsi','pres']
  efit_scalar_sig_names: ['li','aminor','kappa','tritop','tribot','volume','betan','betap','rmaxis', 'zmaxis','wmhd','drsep','zxpt1','zxpt2','rxpt1','rxpt2','seplim', 'gapin', 'gapout', 'gapbot', 'gaptop']
  efit_type: 'EFIT01'
  include_psirz: False
  include_rhovn: True
  thomson_sig_names: [] #['density', 'temp']
  include_thomson_uncertainty: True
  cer_sig_names: [] #['temp','rot']
  cer_type: 'CERQUICK'
  cer_realtime_channels: True
  cer_rotation_units_of_khz: True
  zipfit_sig_names: ['trotfit','edensfit','etempfit','itempfit'] #,'idensfit']
#['ftscrot','ftscpsin','ftsc1vld','ftsspsin','ftssrot','etscr','etscrin','etscrout','etsct','etsctin']
# ['etste', 'etsne','etscr','etsct',
#                'etstein', 'etsnein','etscrin', 'etsctin','etsinq', 'etsinprs',
#                'etsteout', 'etsneout', 'etsqout', 'etsprsout',
#                'etste', 'etsne','etscr','etsct']
  pcs_sig_names: []
  include_radiation: False
  include_full_ech_data: True
  include_full_nb_data: True
  include_gas_valve_info: True
  num_x_points: 33
  trial_fits: [] #['spline_1d','linear_interp_1d','mtanh_1d', 'csaps_1d']
logistics:
  output_file: /cscratch/mehtav/new_data.h5
  overwrite_shots: True
  num_processes: 1
  max_shots_per_run: 1000
