data:
#shots=np.load('new_shots.npy')
#shots = [187076] #[185769] #[163303,175970] #175970 is Colin's good modulation shot; 154764 is David Eldon's
  shots: [163303,187076]
  tmin: 0
  tmax: 6000
  time_step: 50
  sql_sig_names: ['t_ip_flat','ip_flat_duration','topology']
  #f'esl019'] #f'bmspinj{i}{j}' for i in ['30','15','21','33'] for j in ['l','r']] #['dstdenp','dssdenest','iptipp',
  #'bt','DUSTRIPPED','ip','N1ICWMTH','N1IIWMTH','echpwr','dsifbonoff']
  scalar_sig_names: [esl019, esl079, esl139, esl199, esl259, esl319, vloop]
  #n1rms
  stability_sig_names: ['n1rms','n2rms','n3rms']
  nb_sig_names: []
  efit_profile_sig_names: []
#['li','aminor','kappa','tritop','tribot','volume']
  efit_scalar_sig_names: ['betap','betan','wmhd']
  efit_type: 'EFIT01'
  include_psirz: False
  include_rhovn: False
#['density', 'temp']
  thomson_sig_names: []
  include_thomson_uncertainty: True
#['temp','rot']
  cer_sig_names: []
  cer_type: 'CERQUICK'
  cer_realtime_channels: True
  cer_rotation_units_of_khz: True
#['trotfit','edensfit','etempfit','itempfit'] #,'idensfit']
  zipfit_sig_names: ['etempfit']
#['ftscrot','ftscpsin','ftsc1vld','ftsspsin','ftssrot','etscr','etscrin','etscrout','etsct','etsctin']
# ['etste', 'etsne','etscr','etsct',
#                'etstein', 'etsnein','etscrin', 'etsctin','etsinq', 'etsinprs',
#                'etsteout', 'etsneout', 'etsqout', 'etsprsout',
#                'etste', 'etsne','etscr','etsct']
  pcs_sig_names: []
  include_radiation: True
#65
  num_x_points: 33
#['linear_interp_1d','mtanh_1d', 'csaps_1d'] #'linear_interp_1d','spline_1d'] #,'mtanh_1d']
  trial_fits: []
logistics:
  output_file: quick_test.h5
  overwrite_shots: True
  num_processes: 1
  max_shots_per_run: 2